# Generated by Django 5.1.4 on 2025-01-18 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_calculation_result_stringrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hp', models.IntegerField(default=0)),
                ('iq', models.IntegerField(default=0)),
                ('happiness', models.IntegerField(default=0)),
            ],
        ),
    ]
